language: java
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get update
  - sudo apt-get install gnupg2 -y
  - sudo gpg2 --list-keys
install:  
  - mvn -s install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -s ./settings.xml
script: 
  - mvn clean install -q
after_success:
  - mvn clean cobertura:cobertura coveralls:report deploy -s ./settings.xml
  - bash <(curl -s https://codecov.io/bash)
