language: java
jdk:
  - oraclejdk8
sudo: false # faster builds

script: 
  - apt-get update && apt-get clean
  - apt-get install gnupg2 -y
  - export GNUPGHOME=./.gnupg
  - gpg2 --list-keys
  - mvn package

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean cobertura:cobertura coveralls:report -s settings.xml
  - mvn deploy -s settings.xml